### ISSUE TITLE
Door Problem

### ISSUE THREAD

**Issue by jimen7** [jimen7/Hazard-Dash#6]
Doors not teleporting to the correct area

**Comment by GrowlingM1ke** [comment]
Fixed the issue. Found out finally how the tiles are read in. Starting from the top left of the screen (0, 0) x represents how many tiles to the right and y how many tiles down, so to fix it you have sort them as follows:

Biggest Y first Then sort by smallest x
This following line is responsible for the sort:
[](sf::Vector2ul a, sf::Vector2ul b) {return (a.y > b.y) || ((a.y == b.y) && (a.x < b.x)); }
Changing the last operator will set if the player teleports from the right or left
